tv-dir: '{{ media-dir }}/tv'
movie-dir: '{{ media-dir }}/movies'
music-dir: '{{ media-dir }}/music'
ebook-dir: '{{ media-dir }}/ebooks'
audiobook-dir: '{{ media-dir }}/audiobooks'
youtube-dir: '{{ media-dir }}/youtube'
download-dir: '{{ media-dir }}/downloads'
seed-dir: '{{ media-dir }}/seeds'
# NFS Mounts
tv-nfs: '{{ nas-ip }}:/tv'
movie-nfs: '{{ nas-ip }}:/movies'
music-nfs: '{{ nas-ip }}:/music'
ebook-nfs: '{{ nas-ip }}:/ebooks'
audiobook-nfs: '{{ nas-ip }}:/audiobooks'
youtube-nfs: '{{ nas-ip }}:/youtube'
download-nfs: '{{ nas-ip }}:/downloads'
seed-nfs: '{{ nas-ip }}:/seeds'
      