---
### ROLE 1 ###
# Trigger Proxmox to provision VM
# Wait for user to complete setup
# Provide user with command for bootscrap script and wait for prompt to exit
- hosts: saturn
  vars_files:
    - /etc/ansible/host_vars/docker.yaml
  roles:
    - provision-vm

- hosts: docker
  roles:
    - common
    - docker



### ROLE 3 - DOCKER ###
# Install Docker & Docker compose
# Pull docker compose files from github
# run docker compose