pve: 
  hosts:
    neptune:
      ansible_host: 
    saturn: 
      ansible_host: 
docker:
  hosts:
    docker:
      ansible_host: 
cameras:
  hosts:
    front-door:
      ansible_host: 
    doorbell:
      ansible_host: 
    front-yard:
      ansible_host: 
    back-yard:
      ansible_host: 
    gazebo:
      ansible_host: 
    garage:
      ansible_host: 
    violet-bedroom:
      ansible_host: 
    baby-monitor:
      ansible_host: 
network:
  hosts:
    router:
      ansible_host:  
    dns: 
      ansible_host: 
    nas:
      ansible_host: 
      