all:
  vars:
    nas-ip: 192.168.100.1
    # Local Directories
    appdata-dir: /opt/appdata
    media-dir: /mnt/media
    # Media Directories
    compose-dir: '{{ media-dir }}/compose'
    backup-dir: '{{ media-dir }}/backup'
    script-dir: '{{ media-dir }}/seeds'
    # NFS Shares
    compose-nfs: '{{ nas-ip }}:/compose'
    backup-nfs: '{{ nas-ip }}:/backup'
    script-nfs: '{{ nas-ip }}:/seeds'
pve: 
  vars:
    pve-user: root
    pve-pass: #SECRETS
  hosts:
    neptune:
      ansible_host: 
      hostname: neptune
      vars:
        pve-host: neptune.mgmt.cbho.me
    saturn: 
      ansible_host: 
      hostname: saturn
      vars:
        pve-host: saturn.mgmt.cbho.me
docker:
  hosts:
    docker-cam:
      ansible_host: 
      hostname: docker-cam
      vars:
        # Media Directories
        cctv-dir: '{{ media-dir }}/cctv'
        # Appdata Directories
        frigate-dir: '{{ appdata-dir }}/frigate'
        # NFS Shares
        compose-nfs: '{{ nas-ip }}:/cctv'
    docker-mgmt:
      ansible_host: 
      hostname: docker-mgmt
      vars:
        # Media Directories
        minio-dir: '{{ media-dir }}/jordan'
        sync-dir: '{{ media-dir }}/sync'
        # NFS Shares
        minio-nfs: '{{ nas-ip }}:/jordan'
        syncthing-dir: '{{ appdata-dir }}/syncthing'
        # NFS Shares
        syncthing-nfs: '{{ nas-ip }}:/syncthing'
    docker-media:
      ansible_host: 
      hostname: docker-media
      vars:
        # Appdata Directories
        plex-dir: '{{ appdata-dir }}/plex'
        tautulli-dir: '{{ appdata-dir }}/tautulli'
        bazarr-dir: '{{ appdata-dir }}/bazarr'
        jellyfin-dir: '{{ appdata-dir }}/jellyfin'
        fileflows-dir: '{{ appdata-dir }}/fileflows'
        npm-dir: '{{ appdata-dir }}/npm'
        ddns-dir: '{{ appdata-dir }}/ddns'
        overseerr-dir: '{{ appdata-dir }}/overseerr'
        doplarr-dir: '{{ appdata-dir }}/doplarr'
    docker-vpn:
      ansible_host: 
      hostname: docker-vpn
      vars:
        # Appdata Directories
        sonarr-dir: '{{ appdata-dir }}/sonarr'
        radarr-dir: '{{ appdata-dir }}/radarr'
        lidarr-dir: '{{ appdata-dir }}/lidarr'
        prowlarr-dir: '{{ appdata-dir }}/prowlarr'
        whisparr-dir: '{{ appdata-dir }}/whisparr'
        stash-dir: '{{ appdata-dir }}/stash-s6'
        readarr-1-dir: '{{ appdata-dir }}/readarr-1'
        readarr-2-dir: '{{ appdata-dir }}/readarr-2'
        sabznbd-dir: '{{ appdata-dir }}/sabnzbd'
        qbittorrent-dir: '{{ appdata-dir }}/qbittorrent'
        tubesync-dir: '{{ appdata-dir }}/tubesync'
        auto-m4b-dir: '{{ appdata-dir }}/audo-m4b'
        flaresolverr-dir: '{{ appdata-dir }}/flaresolverr'
        # Media Directories
        deprecated-dir: '{{ media-dir }}/deprecated'
        # NFS Mounts
        deprecated-nfs: '{{ nas-ip }}/deprecated'
media:
  vars:
    # Media Directories
    tv-dir: '{{ media-dir }}/tv'
    movie-dir: '{{ media-dir }}/movies'
    music-dir: '{{ media-dir }}/music'
    ebook-dir: '{{ media-dir }}/ebooks'
    audiobook-dir: '{{ media-dir }}/audiobooks'
    youtube-dir: '{{ media-dir }}/youtube'
    download-dir: '{{ media-dir }}/downloads'
    seed-dir: '{{ media-dir }}/seeds'
    # NFS Mounts
    tv-nfs: '{{ nas-ip }}:/tv'
    movie-nfs: '{{ nas-ip }}:/movies'
    music-nfs: '{{ nas-ip }}:/music'
    ebook-nfs: '{{ nas-ip }}:/ebooks'
    audiobook-nfs: '{{ nas-ip }}:/audiobooks'
    youtube-nfs: '{{ nas-ip }}:/youtube'
    download-nfs: '{{ nas-ip }}:/downloads'
    seed-nfs: '{{ nas-ip }}:/seeds'
  hosts:
    docker-media:
    docker-vpn:

cameras:
  hosts:
    docker-cam:
      ansible_host: 
      hostname: docker-cam
      