---

# - name: Configuring Virtual Machines
#   hosts: neptune
#   vars_files:
#     - /mnt/c/Users/Christian/Documents/Repos/ansible/host_vars/docker.yaml
#   gather_facts: false
#   roles:
#     - provision-vm

- name: Running Common Config
  hosts: docker-hosts
  roles:
    - common

- name: Running ZSH Config
  hosts: docker-hosts
  vars:
    ansible_user: christian
  roles:
    - zsh

# - name: Running Docker Config
#   hosts: docker
#   roles:
#     - docker
