---
# PROXMOX CONFIG
- name: Configuring Virtual Machines
  hosts: saturn
  gather_facts: no
  tasks:
    - include: tasks/proxmox-provision.yml
# PROXMOX CONFIG
- name: Bootstrapping Clients
  hosts: docker-media
  gather_facts: no
  tasks:
    - include: tasks/proxmox-provision.yml
# NETWORK CONFIG
- name: Confguring Media VM Networking
  hosts: docker-media
  gather_facts: no
  tasks:
    - include: tasks/network-media.yml
- name: Confguring VPN VM Networking
  hosts: docker-vpn
  gather_facts: no
  tasks:
    - include: tasks/network-vpn.yml
- name: Confguring Cam VM Networking
  hosts: docker-cam
  gather_facts: no
  tasks:
    - include: tasks/network-cam.yml
- name: Confguring MGMT VM Networking
  hosts: docker-mgmt
  gather_facts: no
  tasks:
    - include: tasks/network-mgmt.yml
# STORAGE CONFIG
- name: Configuring Global Storage
  hosts: docker
  gather_facts: no
  tasks:
    - include: tasks/storage-all.yml
- name: Confguring Media VM Storage
  hosts: docker-media
  gather_facts: no
  tasks:
    - include: tasks/storage-media.yml
- name: Confguring VPN VM Storage
  hosts: docker-vpn
  gather_facts: no
  tasks:
    - include: tasks/storage-vpn.yml
- name: Confguring Cam VM Storage
  hosts: docker-cam
  gather_facts: no
  tasks:
    - include: tasks/storage-cam.yml
- name: Confguring MGMT VM Storage
  hosts: docker-mgmt
  gather_facts: no
  tasks:
    - include: tasks/storage-mgmt.yml
# APPDATA RESTORE
- name: Restoring Media VM Appdata
  hosts: docker-media
  gather_facts: no
  tasks:
    - include: tasks/restore-media.yml
- name: Restoring VPN VM Appdata
  hosts: docker-vpn
  gather_facts: no
  tasks:
    - include: tasks/restore-vpn.yml
- name: Restoring Cam VM Appdata
  hosts: docker-cam
  gather_facts: no
  tasks:
    - include: tasks/restore-cam.yml
- name: Restoring MGMT VM Appdata
  hosts: docker-mgmt
  gather_facts: no
  tasks:
    - include: tasks/restore-mgmt.yml
# APPDATA PERMISSIONS
- name: Setting Appdata Permissions
  hosts: docker
  gather_facts: no
  tasks:
    - include: tasks/permissions-all.yml
# DOCKER INSTALL
- name: Globally Installing Docker
  hosts: docker
  vars:
    pip_install_packages:
      - name: docker
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
# DOCKER CREATION
- name: Creating Media Dockers
  hosts: docker-media
  gather_facts: no
  tasks:
    - include: tasks/docker-media.yml
- name: Creating VPN Dockers
  hosts: docker-vpn
  gather_facts: no
  tasks:
    - include: tasks/docker-vpn.yml
- name: Creating Cam Dockers
  hosts: docker-cam
  gather_facts: no
  tasks:
    - include: tasks/docker-cam.yml
- name: Creating MGMT Dockers
  hosts: docker-mgmt
  gather_facts: no
  tasks:
    - include: tasks/docker-media.yml
# BACKUP CONFIGURATION
- name: Configure Media VM Backups
  hosts: docker-media
  gather_facts: no
  tasks:
    - include: tasks/backup-media.yml
- name: Configure VPN VM Backups
  hosts: docker-vpn
  gather_facts: no
  tasks:
    - include: tasks/backup-vpn.yml
- name: Configure Cam VM Backups
  hosts: docker-cam
  gather_facts: no
  tasks:
    - include: tasks/backup-cam.yml
- name: Configure MGMT VM Backups
  hosts: docker-mgmt
  gather_facts: no
  tasks:
    - include: tasks/backup-mgmt.yml