---
os_pkg:
git_full_name: Firstname Lastname
git_email: email@domain.com

all_media_dirs:
group_media_dirs:
host_media_dirs:
all_appdata_dirs:
group_appdata_dirs:
host_appdata_dirs:

create_home: false
system: false