- name: Configuring Network Interfaces
  network_state:
    interfaces:
      - name: net0
        type: ethernet
        state: up
        ipv4:
          enabled: true
          dhcp: true
      - name: net1
        type: ethernet
        state: up
        ipv4:
          enabled: true
          address:
            - ip: 192.168.100.4
              prefix-length: 24
          auto-dns: false
          dhcp: false
        ipv6:
          enabled: false