- name: Creating TV Media Directory
  ansible.builtin.file:
    path: '{{ tv-dir }}'
    state: directory
    mode: '0755'
- name: Mounting TV NFS Share
  ansible.posix.mount:
    src: '{{ tv-nfs }}'
    path: '{{ tv-dir }}'
    opts: rw,sync,hard
    state: mounted
    fstype: nfs
    boot: true
- name: Creating Deprecated Media Directory
  ansible.builtin.file:
    path: '{{ deprecated-dir }}'
    state: directory
    mode: '0755'
- name: Mounting Deprecated NFS Share
  ansible.posix.mount:
    src: '{{ deprecated-nfs }}'
    path: '{{ deprecated-dir }}'
    opts: rw,sync,hard
    state: mounted
    fstype: nfs
    boot: true
- name: Creating Movie Media Directory
  ansible.builtin.file:
    path: '{{ movie-dir }}'
    state: directory
    mode: '0755'
- name: Mounting Movie NFS Share
  ansible.posix.mount:
    src: '{{ movie-nfs }}'
    path: '{{ movie-dir }}'
    opts: rw,sync,hard
    state: mounted
    fstype: nfs
    boot: true
- name: Creating YouTube Media Directory
  ansible.builtin.file:
    path: '{{ youtube-dir }}'
    state: directory
    mode: '0755'
- name: Mounting YouTube NFS Share
  ansible.posix.mount:
    src: '{{ youtube-nfs }}'
    path: '{{ youtube-dir }}'
    opts: rw,sync,hard
    state: mounted
    fstype: nfs
    boot: true
- name: Creating Music Media Directory
  ansible.builtin.file:
    path: '{{ music-dir }}'
    state: directory
    mode: '0755'
- name: Mounting Music NFS Share
  ansible.posix.mount:
    src: '{{ music-nfs }}'
    path: '{{ music-dir }}'
    opts: rw,sync,hard
    state: mounted
    fstype: nfs
    boot: true
- name: Creating Audiobook Media Directory
  ansible.builtin.file:
    path: '{{ audiobook-dir }}'
    state: directory
    mode: '0755'
- name: Mounting Audiobook NFS Share
  ansible.posix.mount:
    src: '{{ audiobook-nfs }}'
    path: '{{ audiobook-dir }}'
    opts: rw,sync,hard
    state: mounted
    fstype: nfs
    boot: true
- name: Creating eBook Media Directory
  ansible.builtin.file:
    path: '{{ ebook-dir }}'
    state: directory
    mode: '0755'
- name: Mounting eBook NFS Share
  ansible.posix.mount:
    src: '{{ ebook-nfs }}'
    path: '{{ ebook-dir }}'
    opts: rw,sync,hard
    state: mounted
    fstype: nfs
    boot: true
- name: Creating Seed Media Directory
  ansible.builtin.file:
    path: '{{ seed-dir }}'
    state: directory
    mode: '0755'
- name: Mounting Seed NFS Share
  ansible.posix.mount:
    src: '{{ seed-nfs }}'
    path: '{{ seed-dir }}'
    opts: rw,sync,hard
    state: mounted
    fstype: nfs
    boot: true
- name: Creating Stash-S6 Appdata Directory
  ansible.builtin.file:
    path: '{{ stash-dir }}'
    state: directory
    mode: '0755'
- name: Creating Sonarr Appdata Directory
  ansible.builtin.file:
    path: '{{ sonarr-dir }}'
    state: directory
    mode: '0755'
- name: Creating Radarr Appdata Directory
  ansible.builtin.file:
    path: '{{ radarr-dir }}'
    state: directory
    mode: '0755'
- name: Creating Lidarr Appdata Directory
  ansible.builtin.file:
    path: '{{ lidarr-dir }}'
    state: directory
    mode: '0755'
- name: Creating Prowlarr Appdata Directory
  ansible.builtin.file:
    path: '{{ prowlarr-dir }}'
    state: directory
    mode: '0755'
- name: Creating Whisparr Appdata Directory
  ansible.builtin.file:
    path: '{{ whisparr-dir }}'
    state: directory
    mode: '0755'
- name: Creating Readarr-1 Appdata Directory
  ansible.builtin.file:
    path: '{{ readarr-1-dir }}'
    state: directory
    mode: '0755'
- name: Creating Readarr-2 Appdata Directory
  ansible.builtin.file:
    path: '{{ readarr-2-dir }}'
    state: directory
    mode: '0755'
- name: Creating Sabnzbd Appdata Directory
  ansible.builtin.file:
    path: '{{ sabnzbd-dir }}'
    state: directory
    mode: '0755'
- name: Creating Qbittorrent Appdata Directory
  ansible.builtin.file:
    path: '{{ qbittorrent-dir }}'
    state: directory
    mode: '0755'
- name: Creating TubeSync Appdata Directory
  ansible.builtin.file:
    path: '{{ tubesync-dir }}'
    state: directory
    mode: '0755'
- name: Creating auto-m4b Appdata Directory
  ansible.builtin.file:
    path: '{{ auto-m4b-dir }}'
    state: directory
    mode: '0755'
- name: Creating flaresolverr Appdata Directory
  ansible.builtin.file:
    path: '{{ flaresolverr-dir }}'
    state: directory
    mode: '0755'