---

- name: Set Facts
  ansible.builtin.set_fact:
    install_pkg: "{{ common_pkg_debian + host_pkgs }}"

- name: Install packages (Debian)
  ansible.builtin.apt:
    pkg:
      - '{{ install_pkg }}'
    update_cache: true
