---

- name: Set Facts
  ansible.builtin.set_fact:
    create_dirs: "{{ all_media_dirs + group_media_dirs + host_media_dirs + all_appdata_dirs + group_appdata_dirs + host_appdata_dirs }}"

- name: Creating Media Directories
  ansible.builtin.file:
    path: '{{ item.dir }}'
    state: directory
    mode: '{{ item.mode }}'
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
  loop: '{{ create_dirs }}'
