---

- name: Set Facts
  ansible.builtin.set_fact:
    create_dirs: "{{ all_media_dirs | ansible.builtin.combine(group_media_dirs) | ansible.builtin.combine(host_media_dirs) | ansible.builtin.combine(all_appdata_dirs) | ansible.builtin.combine(group_appdata_dirs) | ansible.builtin.combine(host_appdata_dirs) }}"

- name: Creating Media Directories
  ansible.builtin.file:
    path: '{{ item.dir }}'
    state: directory
    mode: '{{ item.mode }}'
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
  loop: '{{ create_dirs }}'
