---

- name: Set Facts
  ansible.builtin.set_fact:
    create_dirs: "{{ media_dirs + appdata_dirs }}"

- name: Creating Media Directories
  ansible.builtin.file:
    path: '{{ item.dir }}'
    state: directory
    mode: '{{ item.mode }}'
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
  loop: '{{ create_dirs }}'
