---

- name: Adding network devices to hostfile
  ansible.builtin.blockinfile:
    state: present
    dest: /etc/hosts
    content: |
        {% for host in groups.network %}
        {{ host }}
        {% endfor %}
  become: true
