---

- name: Mounting Global NFS Shares
  ansible.posix.mount:
    src: '{{ item.mnt }}'
    path: '{{ item.dir }}'
    opts: user,rw,hard,intr
    state: mounted
    fstype: nfs
    boot: true
  loop: "{{ all_nfs_mounts }}"
  become: true

- name: Mounting Group NFS Shares
  ansible.posix.mount:
    src: '{{ item.mnt }}'
    path: '{{ item.dir }}'
    opts: user,rw,hard,intr
    state: mounted
    fstype: nfs
    boot: true
  loop: "{{ group_nfs_mounts }}"
  become: true