---

- name: Install dependencies (Debian)
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add GPG key (Debian)
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add docker repository to apt (Debian)
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/debian bookworm stable"
    state: present

- name: Install docker (Debian)
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
