---
- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add docker repository to apt
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/debian bionic stable
    state: present

- name: Install docker
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin

- name: Check docker is active
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Adding remote user to docker group
  ansible.builtin.user:
    name: "{{ my_user }}"
    groups: docker
    append: true

- name: Install docker-compose
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /usr/local/bin/docker-compose
    owner: "{{ my_user }}"
    group: "{{ my_user }}"
