---
- name: Run Debian-specific tasks
  ansible.builtin.include_tasks: debian.yaml
  when: ansible_os_family == "Debian"

- name: Check docker is active
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Manage Users and Groups
  ansible.builtin.include_tasks: users.yaml

- name: Install docker-compose
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /usr/local/bin/docker-compose
    owner: "{{ my_user }}"
    group: 1001

# - name: Clone docker-compose repo from github
- name: Clone docker-compose repository
  ansible.builtin.git:
    repo: 'https://github.com/cbhomelab/'
    dest: /tmp/checkout
# - name: Copy compose environment files from ansible host
