---
- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Adding users to "docker" group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop:
    - docker
    - "{{ my_user }}"
