---
- name: Configuring Virtual Machines
  hosts: pve
  gather_facts: no
  tasks:
    - include: tasks/proxmox-provision.yml

- name: Bootstrapping Clients
  hosts: vms
  gather_facts: no
  tasks:
    - include: tasks/proxmox-provision.yml

- name: Running Common Config
  hosts: vms
  gather_facts: no
  roles:
    - common
