---

- name: Configuring Virtual Machines
  hosts: pve
  vars_files:
    - /etc/ansible/host_vars/docker.yaml
  gather_facts: false
  roles:
    - provision-vm

- name: Running Common Config
  hosts: docker
  roles:
    - common

- name: Running Docker Config
  hosts: docker
  roles:
    - docker
