---

- name: Configuring Virtual Machines
  hosts: pve
  gather_facts: no
  roles:
    - provision-vm

- name: Running Common Config
  hosts: vms
  roles:
    - common

- name: Running Docker Config
  hosts: docker
  roles:
    - docker